/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javafx_calculator;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.stage.Stage;

import javafx.scene.layout.GridPane;

import java.io.IOException;
import java.net.URL;

public class App extends Application {
    @Override
    public void start(Stage stage) throws IOException {
        URL xmlResource = getClass().getResource("/ui/calc-monolithic-controller.xml");
        GridPane gp = FXMLLoader.load(xmlResource);

        //create Scene, we can pass gp to its constructor as the root of the Scene:
        Scene scene = new Scene(gp, 640, 480);

        URL cssResource = getClass().getResource("/ui/calcbuttons.css");
        scene.getStylesheets().add(cssResource.toString());


        //A window is called a stage
        stage.setScene(scene);
        stage.show();
    }
    public static void main(String[] args){
        launch();
    }
}